FROM node:16-alpine

WORKDIR /usr/src/app

COPY ./packages ./packages

COPY ./package.json ./package.json
COPY ./turbo.json ./turbo.json

COPY ./apps/web ./apps/web

RUN npm install

RUN npm run db:generate
RUN DATABASE_URL=${DATABASE_URL} npm run build

EXPOSE 3000

CMD ["npm", "start"]