services:
  - type: web
    name: http-server
    env: node
    buildCommand: |
      npm install
      cd packages/db
      npx prisma generate
      npx prisma migrate deploy
      cd ../..
      npm run build
    startCommand: npm start
    envVars:
      - key: DATABASE_URL
        value: your-database-url